language: objective-c
osx_image: xcode8.3
xcode_workspace: pilot.xcworkspace
xcode_scheme: pilot
xcode_sdk: iphonesimulator10.3

script: set -o pipefail && xcodebuild test -workspace pilot.xcworkspace -scheme pilot -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' | xcpretty

